# Generated by Django 4.2.30 on 2026-09-10 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='集群名称')),
                ('environment', models.CharField(choices=[('prod', '生产'), ('staging', '预发'), ('test', '测试'), ('dev', '开发')], default='prod', max_length=16, verbose_name='环境')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '集群',
                'verbose_name_plural': '集群',
                'db_table': 'db_cluster',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='部门名称')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='部门编码')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '部门',
                'verbose_name_plural': '部门',
                'db_table': 'db_department',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=512)),
                ('status_code', models.PositiveIntegerField(default=0)),
                ('duration_ms', models.FloatField(db_index=True, default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': '请求耗时日志',
                'verbose_name_plural': '请求耗时日志',
                'db_table': 'db_request_log',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='InstanceStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_date', models.DateField(db_index=True, verbose_name='统计日期')),
                ('instance_count', models.PositiveIntegerField(default=0, verbose_name='实例数量')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instance_stats', to='dbmanager.cluster', verbose_name='集群')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instance_stats', to='dbmanager.department', verbose_name='部门')),
            ],
            options={
                'verbose_name': '实例统计',
                'verbose_name_plural': '实例统计',
                'db_table': 'db_instance_stat',
                'ordering': ['-stat_date', 'department_id', 'cluster_id'],
            },
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='实例名称')),
                ('host', models.CharField(max_length=255, verbose_name='主机')),
                ('port', models.PositiveIntegerField(verbose_name='端口')),
                ('db_type', models.CharField(choices=[('mysql', 'MySQL'), ('postgresql', 'PostgreSQL'), ('redis', 'Redis'), ('mongodb', 'MongoDB'), ('other', 'Other')], default='mysql', max_length=32, verbose_name='数据库类型')),
                ('username', models.CharField(blank=True, default='', max_length=128, verbose_name='账号')),
                ('password_encrypted', models.TextField(blank=True, default='', verbose_name='加密密码')),
                ('password_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='密码更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='dbmanager.cluster', verbose_name='所属集群')),
            ],
            options={
                'verbose_name': '实例',
                'verbose_name_plural': '实例',
                'db_table': 'db_instance',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='cluster',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clusters', to='dbmanager.department', verbose_name='所属部门'),
        ),
        migrations.AddConstraint(
            model_name='instancestat',
            constraint=models.UniqueConstraint(fields=('stat_date', 'cluster'), name='uniq_stat_date_cluster'),
        ),
        migrations.AddIndex(
            model_name='instance',
            index=models.Index(fields=['host', 'port'], name='db_instance_host_88668f_idx'),
        ),
        migrations.AddIndex(
            model_name='instance',
            index=models.Index(fields=['cluster', 'is_active'], name='db_instance_cluster_cbb302_idx'),
        ),
        migrations.AddConstraint(
            model_name='instance',
            constraint=models.UniqueConstraint(fields=('host', 'port'), name='uniq_instance_host_port'),
        ),
        migrations.AddConstraint(
            model_name='cluster',
            constraint=models.UniqueConstraint(fields=('department', 'name'), name='uniq_dept_cluster_name'),
        ),
    ]
